Feature/#15
lassl/tokenizer pull request #16
Opened 2021-04-26 12:35 UTC by bzantium

2021-04-26 13:15 UTC, soeque1 reviewed
- 수정 사항들이 <오류 없이 작동되는 것이 보장되면> 좋은 수정 방향이라고 생각됩니다.

2021-04-26 13:46 UTC, soeque1 requested changes
README의 Run 예시 검토를 부탁드립니다.

2021-04-27 00:17 UTC, bzantium commented
> @bzantium
> 리팩토링 되면
> 
> `python train.py tokenizer.pre_tokenizer=cbpe_whitespace tokenizer.subword_tokenizer=cbpe`
> 
> 이렇게 수정 되야 하는건가요?

아닙니다. 리팩토링되면 아래와 같이 한 번만 입력하면 됩니다.
```bash
python train.py tokenizer=cbpe_whitespace
```

2021-04-27 00:18 UTC, bzantium commented
> README의 Run 예시 검토를 부탁드립니다.

네 README에도 해당 사항 변경하겠습니다 :)

2021-04-29 07:29 UTC, soeque1 approved these changes

2021-05-01 00:57 UTC, aisolab commented
> > README의 Run 예시 검토를 부탁드립니다.
> 
> 네 README에도 해당 사항 변경하겠습니다 :)

이 내용이 반영도어있으면 merge 부탁드립니다. @bzantium

2021-05-01 07:06 UTC, merged